services:

  Vinatis\Bundle\SecurityLdapBundle\Manager\UserLdapManager:
    arguments:
      - '@Vinatis\Bundle\SecurityLdapBundle\Service\ActiveDirectory'
      - '@security.password_encoder'
      - '%vinatis_security_ldab.entity.class%'

  Vinatis\Bundle\SecurityLdapBundle\Bridge\Symfony\Security\Authenticator\LdapAuthenticator:
    arguments:
      - '@Vinatis\Bundle\SecurityLdapBundle\Manager\UserLdapManager'
      - '@Vinatis\Bundle\SecurityLdapBundle\Service\ActiveDirectory'
      - '@Lexik\Bundle\JWTAuthenticationBundle\Encoder\JWTEncoderInterface'
      - '@Doctrine\ORM\EntityManagerInterface'
      - '@Gesdinet\JWTRefreshTokenBundle\Model\RefreshTokenManagerInterface'